package com.kissaki.client;

public interface KickStatusInterface {
	static final int STATUS_KICK_APPINITIALIZE = -1;
	
	static final int STATUS_KICK_TESTVIEW_INIT = 0;
	
	static final int STATUS_KICK_TESTVIEW_PROC = STATUS_KICK_TESTVIEW_INIT+1;
	
	static final int STATUS_KICK_LOGIN_INIT = STATUS_KICK_TESTVIEW_PROC+1;
	static final int STATUS_KICK_LOGIN_PROC = STATUS_KICK_LOGIN_INIT+1;
	static final int STATUS_KICK_LOGIN_SUCCEEDED = STATUS_KICK_LOGIN_PROC+1;
	
	
	static final int STATUS_KICK_LOADING_INIT = STATUS_KICK_LOGIN_SUCCEEDED+1;
	static final int STATUS_KICK_LOADING_PROC = STATUS_KICK_LOADING_INIT+1;
	
	static final int STATUS_KICK_LOADING_USER_INIT = STATUS_KICK_LOADING_PROC+1;
	static final int STATUS_KICK_LOADING_USER_PROC = STATUS_KICK_LOADING_USER_INIT+1;
	
	
	static final int STATUS_KICK_OWN_INIT = STATUS_KICK_LOADING_USER_PROC+1;
	static final int STATUS_KICK_OWN_PROC = STATUS_KICK_OWN_INIT+1;
	
	static final int STATUS_KICK_OWNERS_INIT = STATUS_KICK_OWN_PROC+1;
	static final int STATUS_KICK_OWNERS_PROC = STATUS_KICK_OWNERS_INIT+1;
	
	static final int STATUS_KICK_OWNERSVIEW_INIT = STATUS_KICK_OWNERS_PROC+1;
	static final int STATUS_KICK_OWNERSVIEW_PROC = STATUS_KICK_OWNERSVIEW_INIT+1;
	
	
	/*
	 * ここからログインする場合の所作
	 */
	static final int STATUS_KICK_OWNERS_INITIALIZE_2 = STATUS_KICK_OWNERS_PROC+1;
	static final int STATUS_KICK_OWNERS_PROC_2 = STATUS_KICK_OWNERS_INITIALIZE_2+1;
	
	static final int STATUS_KICK_OUTED_INIT = STATUS_KICK_OWNERS_PROC_2+1;
	static final int STATUS_KICK_OUTED_PROC = STATUS_KICK_OUTED_INIT+1;
	
}
